linters-settings:
  errcheck:
    # do not report about not checking errors in type assertions: `a :=
    # b.(MyStruct)`
    check-type-assertions: false

    # do not report about assignment of errors to blank identifier: `num, _ :=
    # strconv.Atoi(numStr)`
    check-blank: false

    # path to a file containing a list of functions to exclude from checking
    # see https://github.com/kisielk/errcheck#excluding-functions for details
    exclude: .errcheck-excludes

linters:
  disable-all: true
  fast: false
  enable:
    - gosimple
    - govet
    - errcheck
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused

