run:
  concurrency: 4
  issues-exit-code: 1

linters:
  disable-all: true
  fast: false
  enable:
    - decorder
    - gci
    - godox
    - gosimple
    - govet
    - ineffassign
    - misspell
    - typecheck
    - unused
